version: "3.3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes: 
    - ./db_data:/var/lib/mysql   

  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    restart: always
    ports: 
      - '8081:80'

  wordpress:
    depends_on: 
    - db
    image: wordpress:latest
    volumes: 
     - ./:/var/www/html
     # - ./wp-content:/var/www/html/wp-content
    ports: 
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress